name: Deploy to GitHub Pages
on:
  push:
    branches: [ master ]
    
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET 5.0 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
        
    - name: Publish .NET Project
      run: dotnet publish ProfessorLookup/ProfessorLookup.csproj -c Release -o release --nologo
      
    - name: Change base tag in index.html from / to ProfessorLookup
      run: sed -i 's/<base href="\/" \/>/<base href="\/ProfessorLookup\/" \/>/g' release/wwwroot/index.html
      
    # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch ProfessorLookup/release/wwwroot/.nojekyll
      
    - name: Commit wwwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: ProfessorLookup/release/wwwroot
